tests / examples2 / unadf: fix permissions tests on MSYS2.
Testing if the executable permission is set on extracted files is
failing on MSYS2 (not 100% sure, but due to lack of such
permissions(?)).

These tests are disabled on MSYS2.

diff --git a/tests/examples2/cmd/unadf/extract_files_to_dir_2_check_permissions_csh b/tests/examples2/cmd/unadf/extract_files_to_dir_2_check_permissions_csh
--- a/tests/examples2/cmd/unadf/extract_files_to_dir_2_check_permissions_csh
+++ b/tests/examples2/cmd/unadf/extract_files_to_dir_2_check_permissions_csh
@@ -1,16 +1,16 @@
 cmd(){
     # check permissions were set on extracted files
-    # (this test is failing on MSYS2:
-    #  -> either the way of checking or permissions are not valid)
 
-    # the test fails(!) -> bug in unadf(!), doing temp. override
-    chmod a+x tmp/${testName}/extract_files_to_dir/csh
-
-    if [ "x${host_type}" != 'xMINGW32' -a \
-         "x${host_type}" != 'xMINGW64' ]
+    # this test is failing on MSYS2
+    #chmod a+x tmp/${testName}/extract_files_to_dir/csh
+    #ls -l tmp/${testName}/extract_files_to_dir/csh 1>&2
+    if [ "x${hostType}" == 'xMINGW32' -o \
+         "x${hostType}" == 'xMINGW64' ]
     then
-        [ -x tmp/${testName}/extract_files_to_dir/csh ]
+        return 0
     fi
+
+    [ -x tmp/${testName}/extract_files_to_dir/csh ]
 }
 
 comment(){
diff --git a/tests/examples2/cmd/unadf/extract_to_dir_2_check_permissions_LZX b/tests/examples2/cmd/unadf/extract_to_dir_2_check_permissions_LZX
--- a/tests/examples2/cmd/unadf/extract_to_dir_2_check_permissions_LZX
+++ b/tests/examples2/cmd/unadf/extract_to_dir_2_check_permissions_LZX
@@ -1,13 +1,16 @@
 cmd(){
     # check permissions were set on extracted files
-    # (this test is failing on MSYS2:
-    #  -> either the way of checking or permissions are not valid)
+
+    # this test is failing on MSYS2
     #chmod a-x tmp/${testName}/extract_to_dir/c/LZX
-    if [ "x${host_type}" != 'xMINGW32' -a \
-         "x${host_type}" != 'xMINGW64' ]
+    #ls -l tmp/${testName}/extract_to_dir/c/LZX 1>&2
+    if [ "x${hostType}" == 'xMINGW32' -o \
+         "x${hostType}" == 'xMINGW64' ]
     then
-        [ -x tmp/${testName}/extract_to_dir/c/LZX ]
+        return 0
     fi
+
+    [ -x tmp/${testName}/extract_to_dir/c/LZX ]
 }
 
 comment(){
